# -*- coding: utf-8 -*-
"""CIE-4practical.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mO9mrvcVs6uBWcm05gLIGnYcXfcKQfAm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
df=pd.read_csv("/content/Mall_Customers.csv")
x=df.iloc[:,[3,4]].values
# Standardize the features
x= StandardScaler().fit_transform(x)
wc=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)
  wc.append(kmeans.inertia_)


plt.plot(range(1,11),wc,marker='o')
plt.title("cluster of elbow method")
plt.xlabel("number of elbow")
plt.ylabel("wc")
plt.show()